# Site settings
title: Core Ideas in Machine Learning
description: A comprehensive study guide to fundamental concepts and ideas in machine learning.
author: Daniil Gusev
url: https://dnlgsv.github.io/core-ml-notes
baseurl: /core-ml-notes

# Repository
repository: dnlgsv/core-ml-notes
github:
  url: https://github.com/dnlgsv/core-ml-notes

# Theme - just-the-docs is perfect for documentation sites
remote_theme: just-the-docs/just-the-docs@v0.7.0

# Just the Docs theme settings
color_scheme: light
search_enabled: true

# Markdown processor
markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: true
  parse_span_html: true
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jemoji

# Collections for organizing content
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post

# Build settings
exclude:
  - .github
  - .gitignore
  - venv
  - docs/_build
  - COMPLETION_CHECKLIST.md
  - STYLING_SUMMARY.md
  - README.md.bak
  - Gemfile
  - Gemfile.lock

# Assets
sass:
  style: compressed
  load_paths:
    - _sass

# Timezone
timezone: UTC
