# Site settings
title: Core Ideas in Machine Learning
description: A comprehensive study guide to fundamental concepts and ideas in machine learning.
author: Daniil Gusev
url: https://dnlgsv.github.io/core-ml-notes
baseurl: /core-ml-notes

# Repository
repository: dnlgsv/core-ml-notes
github:
  url: https://github.com/dnlgsv/core-ml-notes

# Theme - Using officially supported GitHub Pages theme
theme: jekyll-theme-slate

# Custom CSS
sass:
  sass_dir: _sass
  style: compressed

# Markdown processor
markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: true
  parse_span_html: true
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jemoji

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
exclude:
  - .github
  - .gitignore
  - venv
  - docs/
  - docs/_build
  - COMPLETION_CHECKLIST.md
  - STYLING_SUMMARY.md
  - README.md.bak
  - Gemfile
  - Gemfile.lock
  - DEPLOYMENT_CHECKLIST.md
  - MIGRATION_SUMMARY.md

# Timezone
timezone: UTC
